! Description: Open-source whitelish
! Last modified: 2026-08-28
! Adult blocklish
! Source from  https://www.ghostery.com/whotracksme/websites

@||facebook.com^
@||fbcdn.net^
@||instagram.com^
@||cdninstagram.com^
@||twitter.com^
@||x.com^
@||t.co^
@||tiktok.com^
@||tiktokcdn.com^
@||tiktokcdn-us.com^
@||ibyteimg.com^
@||ibytedtos.com^
@||snapchat.com^
@||discord.com^
@||discordapp.com^
@||line.me^
@||telegram.org^
@||t.me^
@||whatsapp.com^
@||wa.me^
@||signal.org^
@||wechat.com^
@||youtube.com^
@||ytimg.com^
@||googlevideo.com^
@||netflix.com^
@||nflxvideo.net^
@||spotify.com^
@||scdn.co^
@||twitch.tv^
@||disneyplus.com^
@||vimeo.com^
@||bilibili.com^
@||googleapis.com^
@||gstatic.com^
@||amazonaws.com^
@||cloudfront.net^
@||cloudflare.com^
@||akamai.net^
@||fastly.net^
@||steampowered.com^
@||steamcommunity.com^
@||steamcontent.com^
@||epicgames.com^
@||epicgames.dev^
@||ea.com^
@||origin.com^
@||gog.com^
@||riotgames.com^
@||playstation.com^
@||nintendo.com^
@||xbox.com^
@||minecraft.net^
@||roblox.com^
@||discord.gg^
@||gojek.com^
@||grab.com^
@||tokopedia.com^
@||shopee.co.id^
@||bca.co.id^
@||mandiri.co.id^
@||bri.co.id^
@||bnl.co.id^
@||bankmandiri.co.id^
@||sucor.co.id^
@||mybca.com^
@||dana.id^
@||ovo.id^
@||gopay.co.id^
@||kemendagri.go.id^
@||kemenkeu.go.id^
@||pajak.go.id^
@||bpjs-kesehatan.go.id^
@||bps.go.id^
@||outlook.com^
@||office.com^
@||microsoft.com^
@||live.com^
@||apple.com^
@||icloud.com^
@||icloud-content.com^
@||googlemail.com^
@||android.com^
@||mozilla.org^
@||wikipedia.org^
@||github.com^
@||gitlab.com^
@||pajak.go.id^
@||djp.go.id^
@||kemenkeu.go.id^
@||sse.pajak.go.id^
@||amazonaws.com^
@||siska.kemenag.go.id^
@||simpatika.kemenag.go.id^
@||emis.kemenag.go.id^
@||kemenag.go.id^
@||pacitankab.go.id^
@@||cmp.osano.com^|
@@||data.promo.timhortons.ca^|
@@||partner.o2online.de^|
@@||data.notify.macys.com^|
@@||om-ssl.consorsbank.de^|
@@|cdn.taboola.com^|
@@||unsubscribe.lhinsights.com^|
@@||belgium.wolterskluwer.com^|
@@||ssai.aniview.com^|
@@||sedge.nfl.com^|
@@||data.orders.costco.ca^|
@@||data.orders.costco.com^|
@@||link.meet5.net^|
@@||link.nzz.ch^|
@@||content.viralize.tv^|
@@||www.datadoghq-browser-agent.com^|
@@||itoya.ec-optimizer.com^|
@@||go.redirectingat.com^|
@@||ref.rbauction.com^|
@@||puzzles-games-api.gp-prod.conde.digital^|
@@||news.warhammer.com^|
@@||prod.impartner.live^|
@@||cdn.atmedia.hu^|
@@||trk.ecomm.lenovo.com^|
@@||s.bluecore.com^|
@@|affiliate.notion.so^|
@@|www3.doubleclick.net^|
@@||acs-m.daraz.pk^|
@@||taiga.maven.io^|
@@||tlh.gedidigital.it^|
@@||smtp.focusgroupresearch.com^|
@@||ap01.records.in.treasuredata.com^|
@@||click.avs.io^|
@@||link.sylikes.com^|
@@||rd.bizrate.com^|
@@|www.daraz.pk^|
@@|daraz.com^|
@@||sbs.demdex.net^|
@@||cl.link-ag.net^|
@@||action.metaffiliation.com^|
@@||www.dogpile.com^|
@@||acs-m.daraz.com.bd^|
@@||f-gear.ec-optimizer.com^|
@@||get.neofinancial.com^|
@@||hidive.com^|
@@||learn.khanacademy.org^|
@@||res.ads.nicovideo.jp^|
@@||sax.sina.com.cn^|
@@||linka.page^|
@@||track.webgains.com^|
@@||secureimage.securedataimages.com^|
@@||infra-api.newrelic.com^|
@@||tms.capitalone.com^|
@@||redir.ownpage.fr^|
@@||tr.rdrtr.com^|
@@||media-consumer365.desigual.com^|
@@||cdn.us*.exponea.com^|
@@||crm-cdn.peek-cloppenburg.com^|
@@||public-cis.exponea.com^|
@@||cdn.rozetka.com.ua^|
@@||vcentry2.valuecommerce.ne.jp^|
@@||recommender.scarabresearch.com^|
@@||refer.discover.com^|
@@||cmp.inmobi.com^|
@@||data.digital.costco.ca^|
@@||data.digital.costco.com^|
@@||api.karte.io^|
@@||sponsor.nitropay.com^|
@@||click.cptrack.de^|
@@|ezodn.com^|
@@||gate.first-id.fr^|
@@||leechers-paradise.org^|
@@||data-*.herz-fuer-tiere.de^|
@@||go.adjust.com^|
@@||clickattr.wayup.com^|
@@||remembering.ca^|
@@||obituaries.toacorn.com^|
@@||obituaries.thestar.com^|
@@||obituaries.therecord.com^|
@@||catchup.thisisdax.com^|
@@||px.a8.net^|
@@||cdn.duurzaam.greenchoice.nl^|
@@||c.office.com^|
@@||surveymyopinion.researchnow.com^|
@@||e.customeriomail.com^|
@@||partner.everydays.de^|
@@||api.docodoco.jp^|
@@||js.monitor.azure.com^|
@@||link.morningbrew.com^|
@@||click.appcast.io^|
@@||anwb.webpower.eu^|
@@||bcicl.*.evergage.com^|
@@||torimochi.line-apps.com^|
@@|core.crazyegg.com^|
@@|app.crazyegg.com^|
@@||oa.tr.line.me^|
@@||stash.roistat.com^|
@@||static-v*.trbo.com^|
@@||api-v*.trbo.com^|
@@||brm-core-*.brsrvr.com^|
@@||marketing.net.idealo-partner.com^|
@@||netatmo.commander1.com^|
@@||vcentry3.valuecommerce.ne.jp^|
@@-ds.metric.gstatic.com^|
@@||id.i2i.jp^|
@@||thumbnail.thench.net^|
@@||validate.perfdrive.com^|
@@||ia.hit.interia.pl^|
@@||analytics.amplitude.com^|
@@|adsterra.com^|
@@|ads.adsterra.com^|
@@|publishers.adsterra.com^|
@@|beta.publishers.adsterra.com^|
@@|partners.adsterra.com^|
@@|beta.partners.adsterra.com^|
@@|affiliates.adsterra.com^|
@@|beta.affiliates.adsterra.com^|
@@|help-advertisers.adsterra.com^|
@@||goto.target.com^|
@@||goto.walmart.com^|
@@||citiintl.122.2o7.net^|
@@||ma135-r.analytics.edgekey.net^|
@@||79423.analytics.edgekey.net^|
@@||classliving.lpages.co^|
@@||home.focusatwill.com^|
@@||health.halodoc.com^|
@@||promo.gramedia.com^|
@@||support-beacon.nakanohito.jp^|
@@||support-widget.nakanohito.jp^|
@@||afi-b.com^|
@@||daikoku.ebis.ne.jp^|
@@||envato.market^|
@@||ac.ebis.ne.jp^|
@@||email.awscloud.com^|
@@||oneline.nextday.media^|
@@|ftp.bmp.ovh^|
@@||cloud.notification-naviextras.com^|
@@||email.elitedangerous.com^|
@@||links.e.theatlantic.com^|
@@||app.appsflyer.com^|
@@||email.procook.co.uk^|
@@||omsc.kpn.com^|
@@||logentries.com^|
@@||email.*.skyeng.ru^|
@@||go.scorptec.com.au^|
@@||links.getblueshift.com^|
@@||click.trafficguard.ai^|
@@||hb.afl.rakuten.co.jp^|
@@||pt.afl.rakuten.co.jp^|
@@||proto2ad.durasite.net^|
@@||tags.crwdcntrl.net^|
@@||official.paymaya.com^|
@@|statcounter.com^|
@@||www.statcounter.com^|
@@||gs.statcounter.com^|
@@||click.virt.s*.exacttarget.com^|
@@||click.virt.exacttarget.com^|
@@||mc.*.exacttarget.com^|
@@||login.sendpulse.com^|
@@||a.sellpoint.net^|
@@||tlaol.com^|
@@||admin.dable.io^|
@@||log.mmstat.com^|
@@||click.simba.taobao.com^|
@@||cs.silverpop.com^|
@@||grp07.ias.rakuten.co.jp^|
@@||cindyholbrook.lpages.co^|
@@||pagead.l.doubleclick.net^|
@@||www.googleadservices.com^|
@@||my.tealiumiq.com^|
@@||artifactory.appodeal.com^|
@@||www.jdoqocy.com^|
@@||cj.dotomi.com^|
@@||intersport.peerius.com^|
@@||cutcaptcha.com^|
@@||forum.notebookreview.com^|
@@||radiofrance.targetspot.com^|
@@||awin1.com^|
@@||app.adjust.com^|
@@||feed.adrelayer.com^|
@@||redirect.appmetrica.yandex.com^|
@@||guce.advertising.com^|
@@||a.adwolf.ru^|
@@||cm-beacon.nakanohito.jp^|
@@||cm-widget.nakanohito.jp^|
@@||ads.tdbank.com^|
@@||nineto5mac-d.openx.net^|
@@||redir.tradedoubler.com^|
@@||clk*.tradedoubler.com^|
@@||href.li^|
@@||str.hit.gemius.pl^|
@@||track.rutarget.ru^|
@@||5471782.fls.doubleclick.net^|
@@||omniture.walmart.com^|
||xhamster.com^$dnsrewrite=NOERROR;;
||pornhub.com^$dnsrewrite=NOERROR;;
||rule34.xxx^$dnsrewrite=NOERROR;;
||xvideos.com^$dnsrewrite=NOERROR;;
||e-hentai.org^$dnsrewrite=NOERROR;;
||chaturbate.com^$dnsrewrite=NOERROR;;
||hitomi.la^$dnsrewrite=NOERROR;;
||erome.com^$dnsrewrite=NOERROR;;
||exhentai.org^$dnsrewrite=NOERROR;;
||imagefap.com^$dnsrewrite=NOERROR;;
||xnxx.com^$dnsrewrite=NOERROR;;
||sxyprn.com^$dnsrewrite=NOERROR;;
||donmai.us^$dnsrewrite=NOERROR;;
||spankbang.com^$dnsrewrite=NOERROR;;
||thisvid.com^$dnsrewrite=NOERROR;;
||tokyomotion.net^$dnsrewrite=NOERROR;;
||fetlife.com^$dnsrewrite=NOERROR;;
||dmm.co.jp^$dnsrewrite=NOERROR;;
||nhentai.net^$dnsrewrite=NOERROR;;
||pornolab.net^$dnsrewrite=NOERROR;;
||dlsite.com^$dnsrewrite=NOERROR;;
||xhamster.desi^$dnsrewrite=NOERROR;;
||pornpics.com^$dnsrewrite=NOERROR;;
||imgsrc.ru^$dnsrewrite=NOERROR;;
||gelbooru.com^$dnsrewrite=NOERROR;;
||stripchat.com^$dnsrewrite=NOERROR;;
||eporner.com^$dnsrewrite=NOERROR;;
||pornhub.org^$dnsrewrite=NOERROR;;
||wnacg.com^$dnsrewrite=NOERROR;;
||boyfriendtv.com^$dnsrewrite=NOERROR;;
||jav.guru^$dnsrewrite=NOERROR;;
||pictoa.com^$dnsrewrite=NOERROR;;
||eroprofile.com^$dnsrewrite=NOERROR;;
||vipergirls.to^$dnsrewrite=NOERROR;;
||tnaflix.com^$dnsrewrite=NOERROR;;
||javlibrary.com^$dnsrewrite=NOERROR;;
||xhamsterlive.com^$dnsrewrite=NOERROR;;
||sankakucomplex.com^$dnsrewrite=NOERROR;;
||onlyfans.com^$dnsrewrite=NOERROR;;
||porntrex.com^$dnsrewrite=NOERROR;;
||hentaifox.com^$dnsrewrite=NOERROR;;
||joyclub.de^$dnsrewrite=NOERROR;;
||cityheaven.net^$dnsrewrite=NOERROR;;
||youporn.com^$dnsrewrite=NOERROR;;
||cam4.com^$dnsrewrite=NOERROR;;
||aznude.com^$dnsrewrite=NOERROR;;
||hentaiera.com^$dnsrewrite=NOERROR;;
||redgifs.com^$dnsrewrite=NOERROR;;
||xgroovy.com^$dnsrewrite=NOERROR;;
||ixxx.com^$dnsrewrite=NOERROR;;
||camwhores.tv^$dnsrewrite=NOERROR;;
||youjizz.com^$dnsrewrite=NOERROR;;
||javbus.com^$dnsrewrite=NOERROR;;
||hqporner.com^$dnsrewrite=NOERROR;;
||planetsuzy.org^$dnsrewrite=NOERROR;;
||ashemaletube.com^$dnsrewrite=NOERROR;;
||fantia.jp^$dnsrewrite=NOERROR;;
||2chan.net^$dnsrewrite=NOERROR;;
||myreadingmanga.info^$dnsrewrite=NOERROR;;
||luxuretv.com^$dnsrewrite=NOERROR;;
||paheal.net^$dnsrewrite=NOERROR;;
||javmix.tv^$dnsrewrite=NOERROR;;
||bestjavporn.com^$dnsrewrite=NOERROR;;
||hentairead.com^$dnsrewrite=NOERROR;;
||pornbb.org^$dnsrewrite=NOERROR;;
||iafd.com^$dnsrewrite=NOERROR;;
||mat6tube.com^$dnsrewrite=NOERROR;;
||elitebabes.com^$dnsrewrite=NOERROR;;
||literotica.com^$dnsrewrite=NOERROR;;
||redtube.com^$dnsrewrite=NOERROR;;
||pornhat.com^$dnsrewrite=NOERROR;;
||xvideos.es^$dnsrewrite=NOERROR;;
||listal.com^$dnsrewrite=NOERROR;;
||porn300.com^$dnsrewrite=NOERROR;;
||thefappeningblog.com^$dnsrewrite=NOERROR;;
||babesource.com^$dnsrewrite=NOERROR;;
||gay-torrents.net^$dnsrewrite=NOERROR;;
||theporndude.com^$dnsrewrite=NOERROR;;
||hanime.tv^$dnsrewrite=NOERROR;;
||ladies.de^$dnsrewrite=NOERROR;;
||svscomics.com^$dnsrewrite=NOERROR;;
||aryion.com^$dnsrewrite=NOERROR;;
||po-kaki-to.com^$dnsrewrite=NOERROR;;
||myfreecams.com^$dnsrewrite=NOERROR;;
||xmoviesforyou.com^$dnsrewrite=NOERROR;;
||livejasmin.com^$dnsrewrite=NOERROR;;
||pmvhaven.com^$dnsrewrite=NOERROR;;
||0xxx.ws^$dnsrewrite=NOERROR;;
||hentaiheroes.com^$dnsrewrite=NOERROR;;
||eroterest.net^$dnsrewrite=NOERROR;;
||naughtyblog.org^$dnsrewrite=NOERROR;;
||tubegalore.com^$dnsrewrite=NOERROR;;
||t66y.com^$dnsrewrite=NOERROR;;
||kaotic.com^$dnsrewrite=NOERROR;;
||vintage-erotica-forum.com^$dnsrewrite=NOERROR;;
||fuq.com^$dnsrewrite=NOERROR;;
||rule34hentai.net^$dnsrewrite=NOERROR;;
||maturetube.com^$dnsrewrite=NOERROR;;
||manyvids.com^$dnsrewrite=NOERROR;;
||apina.biz^$dnsrewrite=NOERROR;;
||beeg.com^$dnsrewrite=NOERROR;;
||alastonsuomi.com^$dnsrewrite=NOERROR;;
||clips4sale.com^$dnsrewrite=NOERROR;;
||doublelist.com^$dnsrewrite=NOERROR;;
||nudevista.com^$dnsrewrite=NOERROR;;
||hentai-covers.site^$dnsrewrite=NOERROR;;
||gaymaletube.com^$dnsrewrite=NOERROR;;
||phun.org^$dnsrewrite=NOERROR;;
||forumophilia.com^$dnsrewrite=NOERROR;;
||javarchive.com^$dnsrewrite=NOERROR;;
||myhentaicomics.com^$dnsrewrite=NOERROR;;
||sehuatang.org^$dnsrewrite=NOERROR;;
||anysex.com^$dnsrewrite=NOERROR;;
||crazyshit.com^$dnsrewrite=NOERROR;;
||tumbex.com^$dnsrewrite=NOERROR;;
||gamcore.com^$dnsrewrite=NOERROR;;
||girlswithmuscle.com^$dnsrewrite=NOERROR;;
||8muses.com^$dnsrewrite=NOERROR;;
||alohatube.com^$dnsrewrite=NOERROR;;
||erofus.com^$dnsrewrite=NOERROR;;
||heavy-r.com^$dnsrewrite=NOERROR;;
||txxx.com^$dnsrewrite=NOERROR;;
||adultwork.com^$dnsrewrite=NOERROR;;
||kitty-kats.net^$dnsrewrite=NOERROR;;
||rosszlanyok.hu^$dnsrewrite=NOERROR;;
||drtuber.com^$dnsrewrite=NOERROR;;
||nozomi.la^$dnsrewrite=NOERROR;;
||celebjihad.com^$dnsrewrite=NOERROR;;
||ukdevilz.com^$dnsrewrite=NOERROR;;
||hentai-foundry.com^$dnsrewrite=NOERROR;;
||sehuatang.net^$dnsrewrite=NOERROR;;
||shalove.net^$dnsrewrite=NOERROR;;
||fap-nation.org^$dnsrewrite=NOERROR;;
||theync.com^$dnsrewrite=NOERROR;;
||multporn.net
||pornoxo.com^$dnsrewrite=NOERROR;;
||melonbooks.co.jp^$dnsrewrite=NOERROR;;
||indexxx.com^$dnsrewrite=NOERROR;;
||luscious.net^$dnsrewrite=NOERROR;;
||hentai2read.com^$dnsrewrite=NOERROR;;
||bodycontact.com^$dnsrewrite=NOERROR;;
||boundhub.com^$dnsrewrite=NOERROR;;
||erosberry.com^$dnsrewrite=NOERROR;;
||shesfreaky.com^$dnsrewrite=NOERROR;;
||ancensored.com^$dnsrewrite=NOERROR;;
||nutaku.net^$dnsrewrite=NOERROR;;
||chyoa.com^$dnsrewrite=NOERROR;;
||adultdvdempire.com^$dnsrewrite=NOERROR;;
||eronity.com^$dnsrewrite=NOERROR;;
||tube8.com^$dnsrewrite=NOERROR;;
||lobstertube.com^$dnsrewrite=NOERROR;;
||yande.re^$dnsrewrite=NOERROR;;
||hentai20.io^$dnsrewrite=NOERROR;;
||javct.net^$dnsrewrite=NOERROR;;
||gate.cc^$dnsrewrite=NOERROR;;
||xstory-fr.com^$dnsrewrite=NOERROR;;
||myhentaigallery.com^$dnsrewrite=NOERROR;;
||sex.com^$dnsrewrite=NOERROR;;
||fap-nation.com^$dnsrewrite=NOERROR;;
||adultempire.com^$dnsrewrite=NOERROR;;
||annunci69.it^$dnsrewrite=NOERROR;;
||paradisehill.cc^$dnsrewrite=NOERROR;;
||asmhentai.com^$dnsrewrite=NOERROR;;
||bongacams.com^$dnsrewrite=NOERROR;;
||adultfriendfinder.com^$dnsrewrite=NOERROR;;
||wikifeet.com^$dnsrewrite=NOERROR;;
||poppen.de^$dnsrewrite=NOERROR;;
||tubepornstars.com^$dnsrewrite=NOERROR;;
||jkforum.net^$dnsrewrite=NOERROR;;
||adulttime.com^$dnsrewrite=NOERROR;;
||freeones.com^$dnsrewrite=NOERROR;;
||xxxdan.com^$dnsrewrite=NOERROR;;
||poringa.net^$dnsrewrite=NOERROR;;
||jjgirls.com^$dnsrewrite=NOERROR;;
||skokka.com^$dnsrewrite=NOERROR;;
||3movs.com^$dnsrewrite=NOERROR;;
||bdsmlr.com^$dnsrewrite=NOERROR;;
||quartier-rouge.be^$dnsrewrite=NOERROR;;
||nuvid.com^$dnsrewrite=NOERROR;;
||analdin.com^$dnsrewrite=NOERROR;;
||hentaicore.net^$dnsrewrite=NOERROR;;
||pornmd.com^$dnsrewrite=NOERROR;;
||jizzbunker.com^$dnsrewrite=NOERROR;;
||naughtyamerica.com^$dnsrewrite=NOERROR;;
||amateri.com^$dnsrewrite=NOERROR;;
||swing-zone.com^$dnsrewrite=NOERROR;;
||kinky.nl^$dnsrewrite=NOERROR;;
||onejav.com^$dnsrewrite=NOERROR;;
||hotmovies.com^$dnsrewrite=NOERROR;;
||eroticbeauties.net^$dnsrewrite=NOERROR;;
||porzo.com^$dnsrewrite=NOERROR;;
||sexlikereal.com^$dnsrewrite=NOERROR;;
||thegay.com^$dnsrewrite=NOERROR;;
||hypnohub.net^$dnsrewrite=NOERROR;;
||xozilla.com^$dnsrewrite=NOERROR;;
||oneclickchicks.com^$dnsrewrite=NOERROR;;
||whatboyswant.com^$dnsrewrite=NOERROR;;
||efukt.com^$dnsrewrite=NOERROR;;
||upornia.com^$dnsrewrite=NOERROR;;
||gayforit.eu^$dnsrewrite=NOERROR;;
||skipthegames.com^$dnsrewrite=NOERROR;;
||ero-video.net^$dnsrewrite=NOERROR;;
||porndig.com^$dnsrewrite=NOERROR;;
||voyeurweb.com^$dnsrewrite=NOERROR;;
||oglaf.com^$dnsrewrite=NOERROR;;
||javfree.me^$dnsrewrite=NOERROR;;
||bravoporn.com^$dnsrewrite=NOERROR;;
||mature.nl^$dnsrewrite=NOERROR;;
||mylust.com^$dnsrewrite=NOERROR;;
||anyporn.com^$dnsrewrite=NOERROR;;
||homemoviestube.com^$dnsrewrite=NOERROR;;
||nijie.info^$dnsrewrite=NOERROR;;
||doujins.com^$dnsrewrite=NOERROR;;
||xcafe.com^$dnsrewrite=NOERROR;;
||javstore.net^$dnsrewrite=NOERROR;;
||dinotube.com^$dnsrewrite=NOERROR;;
||thehun.net^$dnsrewrite=NOERROR;;
||showup.tv^$dnsrewrite=NOERROR;;
||konachan.com^$dnsrewrite=NOERROR;;
||sexemodel.com^$dnsrewrite=NOERROR;;
||zbiornik.com^$dnsrewrite=NOERROR;;
||forcedcinema.net^$dnsrewrite=NOERROR;;
||swinglifestyle.com^$dnsrewrite=NOERROR;;
||freevideo.cz^$dnsrewrite=NOERROR;;
||shemalestardb.com^$dnsrewrite=NOERROR;;
||xvideos2.com^$dnsrewrite=NOERROR;;
||rec-tube.com^$dnsrewrite=NOERROR;;
||jacquieetmichel.net^$dnsrewrite=NOERROR;;
||pornovideoshub.com^$dnsrewrite=NOERROR;;
||krx18.com^$dnsrewrite=NOERROR;;
||bbs-tw.com^$dnsrewrite=NOERROR;;
||hotpornfile.org^$dnsrewrite=NOERROR;;
||thumbzilla.com^$dnsrewrite=NOERROR;;
||porn-w.org^$dnsrewrite=NOERROR;;
||squirt.org^$dnsrewrite=NOERROR;;
||dumbingofage.com^$dnsrewrite=NOERROR;;
||boy18tube.com^$dnsrewrite=NOERROR;;
||iwank.tv^$dnsrewrite=NOERROR;;
||shooshtime.com^$dnsrewrite=NOERROR;;
||xrares.com^$dnsrewrite=NOERROR;;
||erotikforum.at^$dnsrewrite=NOERROR;;
||storiesonline.net^$dnsrewrite=NOERROR;;
||voyeurhit.com^$dnsrewrite=NOERROR;;
||mgstage.com^$dnsrewrite=NOERROR;;
||tubepornclassic.com^$dnsrewrite=NOERROR;;
||adultdvdtalk.com^$dnsrewrite=NOERROR;;
||njav.tv^$dnsrewrite=NOERROR;;
||porndroids.com^$dnsrewrite=NOERROR;;
||freeadultcomix.com^$dnsrewrite=NOERROR;;
||mysw.info^$dnsrewrite=NOERROR;;
||xbooru.com^$dnsrewrite=NOERROR;;
||gayporno.fm^$dnsrewrite=NOERROR;;
||voyeur-house.tv^$dnsrewrite=NOERROR;;
||u18chan.com^$dnsrewrite=NOERROR;;
||xchat.cz^$dnsrewrite=NOERROR;;
||kink.com^$dnsrewrite=NOERROR;;
||iceporn.com^$dnsrewrite=NOERROR;;
||freexcafe.com^$dnsrewrite=NOERROR;;
||javpop.com^$dnsrewrite=NOERROR;;
||zootube1.com^$dnsrewrite=NOERROR;;
||scrolller.com^$dnsrewrite=NOERROR;;
||mmsgram.com^$dnsrewrite=NOERROR;;
||vjav.com^$dnsrewrite=NOERROR;;
||kleverig.eu^$dnsrewrite=NOERROR;;
||nudography.com^$dnsrewrite=NOERROR;;
||vrporn.com^$dnsrewrite=NOERROR;;
||katestube.com^$dnsrewrite=NOERROR;;
||pornoplus.fr^$dnsrewrite=NOERROR;;
